version: 0.2

phases:
  install:
    runtime-versions:
      dart: 3.4.1
    commands:
      - dart pub get
  pre_build:
    commands:
      - dart_frog build
  build:
    commands:
      - cd build
      - docker build -t shamansharif/minimal-cv .
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - "**/*"
